### ISSUE TITLE
Problem win set set theme

### ISSUE THREAD

**Issue by chrom** [gosukiwi/vim-atom-dark#6]
Prompt please in what a problem?[
<img width="582" alt="screen shot 2018-03-10 at 23 09 07" src="https://user-images.githubusercontent.com/944310/37246778-820a922e-24b8-11e8-9e79-1c8ce5d3c6f2.png">
](url)

**Comment by gosukiwi** [comment]
Those don't look like errors related to the theme. Try turning it off in your `.vimrc` and opening Vim again.

**Comment by vaklinzi** [comment]
I had the same problem when I downloaded the theme with **wget**. Maybe it adds some html metadata, but when I downloaded the theme directly from here, it works properly. Thanks

**Comment by gosukiwi** [comment]
Interesting, thanks for sharing! I'll close this issue then.
